# Database configuration
# Uses PostgreSQL when DATABASE_URL is set (production/Heroku)
# Falls back to SQLite for local development

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <% if ENV["DATABASE_URL"] %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3
  timeout: 5000
  <% end %>

# Test always uses SQLite for speed
test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3
  timeout: 5000

# Production uses DATABASE_URL (Heroku) or PostgreSQL config
production:
  <% if ENV["DATABASE_URL"] %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ryde_production
    username: ryde
    password: <%= ENV["RYDE_DATABASE_PASSWORD"] %>
  <% end %>
